// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKqQewteYMQlT4vlyPI-FL5ARUKKB3V1Y',
    appId: '1:191174930610:web:66fd86dd0d8ca3bdcbd9ab',
    messagingSenderId: '191174930610',
    projectId: 'teste-esp32-e9fab',
    authDomain: 'teste-esp32-e9fab.firebaseapp.com',
    databaseURL: 'https://teste-esp32-e9fab-default-rtdb.firebaseio.com',
    storageBucket: 'teste-esp32-e9fab.appspot.com',
    measurementId: 'G-GPVKV7NDVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCucgNcbC7pK95W8UMD2dmVElxs9bLDRqA',
    appId: '1:191174930610:android:97b861e9c75159b4cbd9ab',
    messagingSenderId: '191174930610',
    projectId: 'teste-esp32-e9fab',
    databaseURL: 'https://teste-esp32-e9fab-default-rtdb.firebaseio.com',
    storageBucket: 'teste-esp32-e9fab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyDBbAK2MwBYXY6CEHkHFRQpCkvvK9NwQ',
    appId: '1:191174930610:ios:0d432286ca5aedb1cbd9ab',
    messagingSenderId: '191174930610',
    projectId: 'teste-esp32-e9fab',
    databaseURL: 'https://teste-esp32-e9fab-default-rtdb.firebaseio.com',
    storageBucket: 'teste-esp32-e9fab.appspot.com',
    iosClientId: '191174930610-sisi3n1jkml8v15pi3rl8r24ub61ktg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.turnled',
  );
}
